### PR TITLE
Bump version to 0.1.10

### PR DESCRIPTION
**Pull request by SoapGentoo**
@erikd for the next release, we need to bump the version number

### CODE REVIEW

**Comment by BenNottelling** [comment]
Readme needs update too

**Comment by erikd** [comment]
I have a bunch of things I check when the version is updated. Having someone else submit this as a PR is probably not useful.

**Comment by SoapGentoo** [comment]
@erikd That's fine, just bump the version number before uploading a new tarball (you updated the release for `sndfile-tools` with the same 1.04 number instead of 1.05)

**Comment by erikd** [comment]
@SoapGentoo I really do not think 1.04 was ever released.

**Comment by SoapGentoo** [comment]
@erikd http://www.mega-nerd.com/libsndfile/tools/:

    The latest version is 1.04 and it can be downloaded here: sndfile-tools-1.04.tar.bz2 ( GPG signature).

Which is a re-release instead of a version bump.

**Comment by erikd** [comment]
As far as I can tell that web page never announced version 1.04, or if it did, do so for no more than a week.

**Comment by SoapGentoo** [comment]
I added 1.04 in Gentoo 1.5 years ago:
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=4ee877b220dc152d1ce62859af765e614f66a9ed

Notice that the `SRC_URI` contains a link to your homepage, i.e., this is not a self-bootstrapped tarball from my side. When generating the hashes, you can see that they changed now:

    --- a/media-sound/sndfile-tools/Manifest
    +++ b/media-sound/sndfile-tools/Manifest
    @@ -1,2 +1,2 @@
     DIST sndfile-tools-1.03.tar.gz 474494 BLAKE2B 17c8f6782895a5e02bcd39e0e966a9196fe26b8fa192b3375a4f167cb554de168d4ce4e638d792720ee3e74483a88060ef9bf6d3713c91834acc9b39427185e2 SHA512 bc6ac7977a95ccf845c889db81452ae84b4f10a8f51c91ddd6fe4d926337a60cdbcb2859b0758816622554bf26a6e42b70f791f2c5158926c3f92ab2abbf14dc
    -DIST sndfile-tools-1.04.tar.bz2 714880 BLAKE2B 14d8f9a8172e4e3d8fe320baf3e546c3998636c0de36e8b41e38e277c18f2af6c3ea944eb4cecdda0e225fa3d7adbcd3a5618e74a9d567c42eb0056f162703e3 SHA512 90b0121f4d0bf3ebf3962cc47bcd6a11e5a644d0567be137a8bcf5881944e03e3c9650c9813c982a58072154f62dd176c46cfe83e5661ff81205db30923b71d3
    +DIST sndfile-tools-1.04.tar.bz2 715692 BLAKE2B e65a222bfdd96803293f006c2c5704fd1037d81524559d86c8e3812b91bd90fa0b47d1f589adb303f68e1ffdbebfd8b4ec616c9f1d897ad993768981c83022e3 SHA512 b93fd74386960c986031fd1652335bc34243bd785ccf31480b82f4d76ef86760ca53173aace273a635db70db46c0c1c4066328aef9c21c01c6e76346dbe56390

**Pull request closed without merging**
