### PR TITLE
Two more places with missing const

### PR DESCRIPTION
**Pull request by milasudril**
Wow, the same text three times.

### CODE REVIEW

**Comment by erikd** [comment]
Would you be able to squash those down to a single commit?

**Comment by milasudril** [comment]
Commits merged

**Comment by erikd** [comment]
I did ask for a rebase against master rather than a merge.

**Comment by milasudril** [comment]
Then i failed to do rebase.

**Comment by erikd** [comment]
Do you want to do it (good learning experience) or should I?

**Comment by milasudril** [comment]
I should really do it so I can learn more about git. Here is what I did

 1. clone my fork on GitHub to a local directory
 2. `git rebase -i HEAD~3`
 3. Squash the two last commits into the first
 4. `git push`
 5. Open new pull request.

I guess that this was not really correct...

**Comment by erikd** [comment]
I think just start with your existing repository then 

1. `git reset --hard HEAD^` to remove the merge commit.
1. Add my repo as a remote name say `upstream` (well documented elsewhere).
1. `git rebase upstream/master`
1. Interactive rebase to squash the two commits.
    `git rebase -i upstream/master`

**Comment by jrlanglois** [comment]
@erikd If it helps any, GitHub provides a means of configuring pull request merging. If you look at the repository's settings, you should be able to only allow Squash and Merge.

**Comment by milasudril** [comment]
Hmm:

    git reset --hard HEAD^
    git remote add upstream https://github.com/erikd/libsamplerate
    git rebase upstream/master

> fatal: Needed a single revision

Also I have some EOL problems:

>        modified:   Make.bat
>        modified:   Win32/Makefile.msvc
>        modified:   Win32/libsamplerate-0.def

**Comment by erikd** [comment]
After you add a remote you need to fetch it using `git fetch <remote name>`.

To fix the EOL problems check the files using `git checkout Make.bat Win32/Makefile.msvc Win32/libsamplerate-0.def`

**Comment by erikd** [comment]
@jrlanglois Squash and merge is often the wrong default and @milasudril did want to use this as a change to learn more about git.

**Comment by milasudril** [comment]
Now there is a new PR. What I did after the clone:

 1. Remove offending rules from .gitattribuets
 2. Checkout .gitattributes
 3. Rebase
 4. Create a new branch
 5. Undo commits in the new branch so it is in its old state
 6. Force-push the new branch to my fork
 7. Checkout matser
 8. Pick up the missing commits by  git fsck --lost-found
 9. push master to my fork

**Pull request closed without merging**
