### PR TITLE
drop libsndfile and alsa

### PR DESCRIPTION
**Pull request by janstary**
* remove the examples, which use sndfile
* drop the libsndfile dependency
* drop alsa, as nothing uses it now
* remove all mentions of sndfile, alsa and examples/ from the build
* remove all mentions of sndfile, alsa and examples/ from the doc
* do not touch the win directories (leaving it to win users )
* remove dead links from the doc while here

Tested on MacOS 10.14.5

### CODE REVIEW

**Comment by janstary** [comment]
Also tested on OpenBSD 6.5/amd64: builds and installs fine,
`make test` says `ok` or `pass` for all tests.

**Comment by janstary** [comment]
Also tested on FreeBSD 12.0/amd64: builds and installs fine,
`make test` says `ok` or `pass` for all tests.

**Comment by erikd** [comment]
Why? Those examples were added because when this code was first released, people we asking for examples on how to use it.

**Comment by janstary** [comment]
```
On Oct 10 20:23:49, erikd@mega-nerd.com wrote:
> Jan Stary wrote:
> > Currently, the sndfile-resample utility that comes with SRC
> > does not have a manpage. See below for one that extends usage();
> 
> Actually, since that program is moving to the sndfile-tools 
> project (so that libsamplerate can drop the libsndfile dependency)
```

And everything in examples/ depends on libsndfile.

**Comment by erikd** [comment]
Yes, but `sndfile-resample` grew from being an example program to something that was useful in its own right. Hence it moved the the `sndfile-tools` repo/project. The other example programs in the `examples/` directory are no useful in their own right, but are good examples and I think worth keeping (regardless of what I may have written before).

**Comment by janstary** [comment]
>> (regardless of what I may have written before).

Well if the libsndfile dependency is staying,
the whole premise of this change is wrong.

**Comment by erikd** [comment]
> Well if the libsndfile dependency is staying, the whole premise of this change is wrong.

Yes, I am afraid that is correct.

**Comment by janstary** [comment]
See instead https://github.com/erikd/libsamplerate/pull/63

**Pull request closed without merging**
